- name: Check s4pred is present
  stat: path={{ app_location }}/s4pread
  register: s4pred_exist
  
- name: Check out s4pred from GIT
  when: s4pred_exist.stat.exists == False
  git:
    repo: https://github.com/psipred/s4pred.git
    dest: "{{ app_location }}/s4pred"
    clone: yes
    force: yes

- name: Initiate virtualenv
  when: s4pred_exist.stat.exists == False
  pip: 
    virtualenv: "{{ app_location }}/s4_env" 
    virtualenv_python: python{{ python_version }}
    requirements: ""

- name: Install dependencies
  when: s4pred_exist.stat.exists == False
  ansible.builtin.pip:
    name:
      - biopython
      - torch
    virtualenv: "{{ app_location }}/s4_env"
    virtualenv_command: /bin/virtualenv
    virtualenv_python: "{{ app_location }}/s4_env/bin/python"

- name: Download s4pred weights 
  when: s4pred_exist.stat.exists == False
  ansible.builtin.get_url:
    url: http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz
    dest: "{{ app_location }}/s4pred/weights.tar.gz"
  
- name: Extract s4pred weights
  when: s4pred_exist.stat.exists == False
  ansible.builtin.unarchive:
    src: "{{ app_location }}/s4pred/weights.tar.gz"
    dest: "{{ app_location }}/s4pred/"
    remote_src: yes
    
- name: remove weights tar.gz
  when: s4pred_exist.stat.exists == False
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/s4pred/weights.tar.gz"
